# -*- coding: utf-8 -*-
"""mapaFinalVD.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18bFU9zu7zWfQZp0ui_ETeDWghr3e9pqt
"""

import folium


# Carga el archivo GeoJSON con los países destacados
geojson_destacados = 'export.geojson'

# Crea un mapa centrado en Sudamérica
mapa = folium.Map(location=[-14.235004,-51.92528], zoom_start=4)

# Define la lista de países y sus ubicaciones geográficas
paises = [
    {'nombre': 'Chile', 'ubicacion': [-33.448889, -70.6692655]},
    {'nombre': 'Argentina', 'ubicacion': [-31.429771, -64.184019]},
    {'nombre': 'Perú', 'ubicacion': [-9.189967, -75.015152]},
    {'nombre': 'Bolivia', 'ubicacion': [-16.290154, -63.588652]}
]

# Define la lista de datos de usuarios para cada red social, en Millones
usuarios_facebook = [12.5, 28.40, 24.8, 7.65]
usuarios_instagram = [11.65, 24.7, 8.9, 1.85]
usuarios_twitter = [2.9, 5.9, 2.2, 0.0004169]

desplazamiento = 1 * (5 / mapa.options['zoom'])

# Agrega una capa de superposición para resaltar los países destacados
folium.GeoJson(geojson_destacados,style_function=lambda feature: {
        'fillColor': 'green', # Cambiar color de relleno
        'color': 'white', # Cambiar color de borde
        'weight': 2, # Cambiar ancho de borde
        'opacity': 0.7 # Cambiar opacidad
    }).add_to(mapa)

# Itera sobre los países y agrega las burbujas al mapa
for i in range(len(paises)):
    # Crea una burbuja con el tamaño según la cantidad de usuarios de Facebook
    if(paises[i]['nombre']=='Argentina'):
      folium.CircleMarker(
          location=[paises[i]['ubicacion'][0]-2*desplazamiento, paises[i]['ubicacion'][1]+1.5*desplazamiento],
          radius=usuarios_facebook[i]*2,
          color='#3b5998',
          fill=True,
          fill_color='#3b5998',
          fill_opacity=0.4,
          tooltip=f"{paises[i]['nombre']}: {usuarios_facebook[i]} millones de usuarios de Facebook"
      ).add_to(mapa)
      
    if(paises[i]['nombre']!='Argentina'):
      folium.CircleMarker(
          location=[paises[i]['ubicacion'][0]-2*desplazamiento, paises[i]['ubicacion'][1]-1.5*desplazamiento],
          radius=usuarios_facebook[i]*2,
          color='#3b5998',
          fill=True,
          fill_color='#3b5998',
          fill_opacity=0.4,
          tooltip=f"{paises[i]['nombre']}: {usuarios_facebook[i]} millones de usuarios de Facebook"
      ).add_to(mapa)
    
    # Crea una burbuja con el tamaño según la cantidad de usuarios de Instagram
    folium.CircleMarker(
        location=[paises[i]['ubicacion'][0], paises[i]['ubicacion'][1]],
        radius=usuarios_instagram[i]*2,
        color='#C13584',
        fill=True,
        fill_color='#C13584',
        fill_opacity=0.4,
        tooltip=f"{paises[i]['nombre']}: {usuarios_instagram[i]} millones de usuarios de Instagram"
    ).add_to(mapa)
    
    # Crea una burbuja con el tamaño según la cantidad de usuarios de Twitter
    folium.CircleMarker(
        location=[paises[i]['ubicacion'][0]+desplazamiento, paises[i]['ubicacion'][1]],
        radius=usuarios_twitter[i]*2,
        color='#1DA1F2',
        fill=True,
        fill_color='#1DA1F2',
        fill_opacity=0.4,
        tooltip=f"{paises[i]['nombre']}: {usuarios_twitter[i]} millones de usuarios de Twitter"
    ).add_to(mapa)
bounds = [[-22.6, -81.2], [-0.7, -58.4]]
mapa.fit_bounds(bounds)
mapa.save('mapa.html')

mapa

